### ISSUE TITLE
Docker/docker-compose deployment

### ISSUE THREAD

**Issue by amandadebler** [nymanjens/piga#1]
Add a docker-compose method for deployment, probably with two containers (app itself and MySQL/MariaDB) and two volumes (app and DB).

Not sure when I'd get around to it, as I have a newborn baby, but I'll let you know here when I do.

**Comment by nymanjens** [comment]
Hi Amanda,

Congratulations with your baby! I have no Docker experience, but I'd be happy to review a pull request to add support for it.

**Comment by nymanjens** [comment]
By coincidence, I got the same request on another project of mine (https://github.com/nymanjens/facto/issues/1), so I decided to dig into Docker a bit.

I added a `docker-compose.yml` with instructions on how to set up a server with Docker in the README
