### ISSUE TITLE
How to make a checkable list with items

### ISSUE THREAD

**Issue by tuxrinku** [nymanjens/piga#2]
I just installed this using docker but when I create a document, I can only type plain text. There's no formatting or any way to create a list with checkboxes or whatever (like in the screenshot). Did I miss something ?

**Comment by nymanjens** [comment]
Here is a list of all the shortcuts, which you can use to add formatting: https://github.com/nymanjens/piga/blob/master/app/js/shared/src/main/scala/app/flux/react/app/document/DesktopTaskEditor.scala#L437-L693

I added a TODO to add a list of these to the README

**Comment by tuxrinku** [comment]
I meant more like how to create something like in your screenshot here : https://github.com/nymanjens/piga/blob/master/screenshot.png

Because I can't find any way to create a checkbox or anything, I'm just in a notepad text editor. If you can provide an example to show how to reproduce the screenshot that would be great

**Comment by nymanjens** [comment]
For getting checkboxes, you just press tab to increase the indentation of your text.

You can use the other shortcuts like ctlr+b for bold and alt+shit+T for tags
